filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.name: juice-shop
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              output.elasticsearch:
                hosts: ["http://elasticsearch:9200"]
                pipeline: "juice-shop-parser"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  pipeline: "juice-shop-parser"
